# Generated by Django 4.1.7 on 2023-03-17 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0002_entry'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='topoc',
            new_name='topic',
        ),
    ]
